# Profile section
profile:
  first_name: Chad
  last_name: Palmer
  # picture: https://rodolfoferro.xyz/assets/images/profile.jpg   # Hosted picture
  picture: static/img/logo.png  # Local picture
  contact:
    address_one: Pflugerville, TX
    address_two:
    phone: (954) 646-2423
  email: chad.n.palmer@gmail.com
  description: I am a highly motivated, recent Computer Science graduate with a passion for all things tech and over a decade of proven leadership experience.


# Social section
social:
  website: https://cpalmer-atx.net
  github: https://github.com/cpalmer-atx
  twitter: https://twitter.com/cpalmer_atx
  linkedin: https://www.linkedin.com/in/cpalmer-atx/


# Experience section
experience:
  item0:
    position: Manufacturing and Test Engineer (Contract)
    company: Pensa Systems
    from: June 2020
    to: October 2020
    description: >
      Contract work to assist in the construction of autonomous drone sub assemblies and completed crafts used for automated grocery inventory tracking. Responsible for writing Python test scripts for respective microcontrollers. Skills used include soldering, inventory tracking, and Python programming including the Tkinter library and Google Sheets API.
    link: http://pensasystems.com/
  item1:
    position: Marine Science Technician
    company: United States Coast Guard
    from: March 2005
    to: July 2015
    description: >
      Led over 1,000 safety & security foreign vessel compliance examinations specializing in shipboard engineering and cargo systems. Discovered key lifesaving, machinery and stability deficiencies resulting in 70+ control actions, first-ever banned vessel from U.S. waters, $1.2 million in fines, and criminal prosecution of responsible parties.
  item2:
    position: Instructor
    company: United States Coast Guard PSC Academy
    from: May 2011
    to: April 2015
    description: >
      Created and delivered 6+ hours of instructional content to 80+ officers from 18 outlying units, resulting in the qualification of 55 service members and expansion of USCG Port State Control examination capacity.
    # link: http://www.nullsec.site
  # item3:
  #   position: Lead ML Engineer
  #   company: Omdena
  #   from: May 2019
  #   to: July 2019
  #   description: >
  #     Lead ML engineer in Omdena's collaborative tree identification challenge to prevent fire outbursts. Contributed with the models developed and the data preprocessing (we develped a Python package for it).
  #   link: https://medium.com/omdena/building-ai-for-good-by-the-people-for-the-people-d98ad78b5001
  # item4:
  #   position: Jr. Python Software Developer
  #   company: CloudLinux
  #   from: February 2019
  #   to: May 2019
  #   description: >
  #     In charge of building automation solutions with Python. The tech stack used includes Scrapy, Luigi, requests, and MongoDB.
  # item5:
  #   position: AI Research Assistant
  #   company: Research Center in Mathematics (CIMAT A.C.)
  #   from: February 2018
  #   to: February 2019
  #   description: >
  #     On charge of doing research and building neural networks for computer vision problems, focused on applications and solutions for real industry issues. Deployed trained models to production.
  # reference: https://rodolfoferro.xyz/resume/


# Education section
education:
  item1:
    institution: Texas State University
    program: 'Bachelor of Science - Computer Science'
    description: Minor - Applied Mathematics
    from: January 2018
    to: May 2020
  item2:
    institution: Austin Community College
    program: Associates of Science - Computer Science
    description: ''
    from: August 2015
    to: December 2019
  # item3:
  #   institution: Harvard University
  #   program: Summer Internship – Adapting machine learning techniques for chemistry problems.
  #   description: Worked on a project to calibrate and predict molecular properties using Gaussian processes.
  #   from: June 2017
  #   to: August 2017
  # reference: https://rodolfoferro.xyz/resume/

# Community section:
community:
  item0:
    institution: Lonestar Dads
    program: Moderator and Events Coordinator
    description: Founding member and group moderator for the largest community of dads ever to exist in Texas. Lonestar Dads is an exclusive community of nearly 4,000 men who come together to become better fathers every day, both individually and together as a brotherhood.  Hunting, camping, fishing trips, father-daughter dances and so much more.
    from: May 2020
    to: Present
    link: https://lonestardads.com
  # item1:
  #   institution: Future Lab
  #   program: Co-founder and Coordinator
  #   description: "Co-founder and coordinator of Future Lab, a community of tech developers for the future. We maily work under three axis: a) Develop awesome tech based projects, b) Share knowledge with the community, and c) Networking with other communities. As a member of Future Lab I have participated on big events such as Talent Land with an AI talk."
  #   from: April 2017
  #   to: Present
  #   link: https://futurelab.mx
  # item2:
  #   institution: GitHub Education
  #   program: GitHub Campus Experts Program
  #   description: Mexican member of the GitHub Campus Experts Program, encouraging to empower other student communities. I also serve as a mentor in different events such as Startup Weekends, hackathons, innovation events, etc.
  #   from: October 2017
  #   to: Present
  #   link: https://githubcampus.expert/RodolfoFerro/
  # item3:
  #   institution: Clubes de Ciencia México
  #   program: Guanajuato Comitee Member and Instructor
  #   description: Co-organizer of the intensive one-week summer science workshops of Clubes de Ciencia México in Guanajuato. Besides organizing, I have participated teaching science workshops (in particular a physics workshop, based on a Nobel Prize design, and artificial intelligence workshops) for high school and undergrad students.
  #   from: January 2015
  #   to: Present
  #   link: https://www.clubesdeciencia.mx
  # item4:
  #   institution: Google Programs
  #   program: Google Student Ambassador and GDG
  #   description: Served as a Google Student Ambassador Latam for the University of Guanajuato, empowering the student community with Googleness and Google technologies to make their life easier. Currently helping the GDG León with tech talks and workshops about AI as a core member of the team. Do cool things that matter.
  #   from: August 2014
  #   to: July 2015
  #   link: https://www.meetup.com/es/GDGLeon/
  # reference: https://rodolfoferro.xyz/resume/



# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - git-alt
  - github
  - raspberry-pi
  - google
  - google-drive
  - slack
  - trello
  - markdown
  - html5
  - bootstrap
  - linux
  - apple
  - windows
extra_skills:
  - C/C++ Programming Language
  - Object Oriented Design
  - Data Structures
  - Linux Command Line
  - VS Code
  - Atom
  - Emotional Intelligence & Conflict Resolution
familiarity:
  - JavaScript
  - Heroku
  - Netlify
  - MongoDB


# Talks and workshops section
# workshops:
#   item0:
#     event: TEDxUNAMLeón
#     workshop: AI in modern times, February 2020.
#     material:
#     link: https://www.ted.com/tedx/events/35293
#   item1:
#     event: PyCon Colombia 2020
#     workshop: 'Workshop – DLaaS: Building cloud-based intelligent solutions, February 2020.'
#     material: https://github.com/RodolfoFerro/PyConCo20
#     link: https://www.pycon.co/ponentes/rodolfo-ferro/
#   item2:
#     event: International Meeting on Artificial Intelligence and its Applications (RIIAA) 2.0.
#     workshop: Workshop – Deep Learning as a Service (DLaaS), August 2019.
#     material: https://github.com/RodolfoFerro/RIIAA19-DLaaS
#     link: https://riiaa.org
#   item3:
#     event: LAB León Web Dev Crash Course 2019.
#     workshop: Crash Course – Introduction to Web Development with Python and Flask, August 2019.
#     material: https://github.com/RodolfoFerro/Flask101
#     link: https://flask101.glitch.me
#   item4:
#     event: DevDay León 2019 by Hackademy.
#     workshop: Workshop – (AI) API development with Python, August 2019.
#     material: https://github.com/RodolfoFerro/PythonBaseAPI
#     link:
#   item5:
#     event: Clubes de Ciencia México 2019.
#     workshop: Workshop – Revealing the Hidden Hyperspectrum with Artificial Neurons, July 2019.
#     material: https://rodolfoferro.xyz/hyperspectrum/
#     link:
#   item6:
#     event: DevDay Mérida 2019.
#     workshop: Workshop – Artificial Intelligence with Python, July 2019.
#     material: https://github.com/RodolfoFerro/DevDayMid2019
#     link:
#   item7:
#     event: Talent Land 2019.
#     workshop: Talk – A.I. in modern times, April 2019.
#     material:
#     link: https://jaliscotalentland2019.sched.com/event/MzAs/inteligencia-artificial-en-tiempos-modernos
#   item8:
#     event: PythonDay México 2018.
#     workshop: Talk – Data Science with Python, December 2018.
#     material: https://github.com/RodolfoFerro/DataSciPy
#     link:
#   item9:
#     event: PythonDay México 2018.
#     workshop: Workshop – Machine Learning as a Service (MLaaS), November 2018.
#     material: https://github.com/RodolfoFerro/MLaaS
#     link:
#   item10:
#     event: HERE Hackathon at Technological University of Leon.
#     workshop: Mentor on the event. Talk – Integration of Technological Solutions, November 2018.
#     material: https://github.com/RodolfoFerro/HereHackathon
#     link:
#   item11:
#     event: 6th. International Conference in Software Engineering Research and Innovation (CONISOFT).
#     workshop: Workshop – Introduction to Neural Networks with Keras, October 2018.
#     material: https://github.com/RodolfoFerro/CONISOFT2018
#     link: http://conisoft.org/2018/public/
#   reference: https://rodolfoferro.xyz/resume/


# Projects section
projects:
  item1:
    title: flask-resume-template
    subtitle: A resume template built with Flask
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    link: https://flask-resume-template.glitch.me
    github: https://github.com/RodolfoFerro/flask-resume-template/
    img: flask-resume-template.png
    tags: [Flask, Python, Bootstrap]
  # item2:
  #   title: DLaaS
  #   subtitle: Google Colab Notebooks
  #   description: A set of Google Colab notebooks and a Flask base API to learn and serve Deep Learning. Prepared for my workshop at RIIAA 2.0.
  #   link: https://rodolfoferro.xyz/RIIAA19-DLaaS/
  #   github: https://github.com/RodolfoFerro/RIIAA19-DLaaS
  #   img: riiaa.png
  #   tags: [Python, Tensorflow 2.0, Keras, Deep Learning]
  # item3:
  #   title: impipes
  #   subtitle: Python package
  #   description: A Python package to build image pipelines in a simple way. Preprocess data to feed neural networks in an easier way.
  #   link: https://impipes.readthedocs.io/en/latest/
  #   github: https://github.com/RodolfoFerro/impipes
  #   img: impipes.png
  #   tags: [Python, PyPI, Images, Data Preprocessing, Documentation]
  # item4:
  #   title: MNIST Web Classifier
  #   subtitle: A CNN served as a web platform
  #   description: Classify handwritten digits directly on your computer or your phone. As simple as taking a picture of a written random multi-digit number.
  #   link: https://flask-micro-template.glitch.me
  #   github: https://github.com/RodolfoFerro/flask-micro-template
  #   img: keras-mnist.png
  #   tags: [Python, Bootstrap, Web Platform, Flask, MNIST, CNN, Keras]
  # item5:
  #   title: EmojiMerida
  #   subtitle: Google Colab Notebook
  #   description: A real-time coding session with an emotion recognizer on facial expressions for a Data Mérida meetup (01/04/2019). The Ai was developed with Python and Keras.
  #   link: https://colab.research.google.com/github/RodolfoFerro/EmojiMerida/blob/master/Data_M%C3%A9rida.ipynb
  #   github:
  #   img: data-merida.png
  #   tags: [Python, Computer Vision, Keras, Neural Networks]
  # item6:
  #   title: PythonBaseAPI
  #   subtitle: API template built with Flask
  #   description: API template built with Python and Flask. Serve an Iris classifier as an API. Content for a workshop.
  #   link: https://docs.google.com/presentation/d/e/2PACX-1vSc7Q82-lwQ8fKgR5WcT7Y0r9kotcYiNuyYjHRlF-fdhf6lkIrF9B_2akvzL-ZQ6ZAyT1lxM9f0mPdx/pub?start=false&loop=false&delayms=3000
  #   github: https://github.com/RodolfoFerro/PythonBaseAPI
  #   img: python-base-api.png
  #   tags: [Flask, Python, API, scikit-learn]
  # item7:
  #   title: flask-micro-template
  #   subtitle: A micro template built with Flask
  #   description: A micro template built with Flask and Bootstrap. Used for minimal testing in Glitch.
  #   link: https://flask-micro-template.glitch.me
  #   github: https://github.com/RodolfoFerro/flask-micro-template
  #   img: flask-micro-template.png
  #   tags: [Flask, Python, Bootstrap]
  # item8:
  #   title: moltransform
  #   subtitle: Python package
  #   description: Molecular transformations for graphic displaying using Cartesian coordinates.
  #   link: https://pypi.org/project/moltransform/
  #   github: https://github.com/RodolfoFerro/moltransform
  #   img: moltransform.png
  #   tags: [Python, PyPI, Molecules, Rigid Transformations]
  # item9:
  #   title: FitbitVersa-SimpleOmnitrix
  #   subtitle: Fitbit Versa Clockface
  #   description: My first clock face for Fitbit Versa, inspired in Ben 10's Omnitrix.
  #   link: https://gallery.fitbit.com/details/6c75fa41-8de0-41db-b851-f21f7447018b
  #   github: https://github.com/RodolfoFerro/FitbitVersa-SimpleOmnitrix
  #   img: simple-omnitrix.png
  #   tags: [TypeScript, Ben 10, Fitbit, Fitbit Versa]


# Certifications and awards section
awards:
  - 'Winner – #TFWorld TF 2.0 Challenge – TensorFlow at Devpost 2020'
  - Academy and Technology – Statal Youth Prize Guanajuato 2018
  - Quantum Computing 101 – IBM Q Certification Badge 2018
  - 1st. Place – HDI Challenge – Talent City Hackathon 2018
  - 1st. Place – SWITCH Hackathon 2017
  - 1st. Place – IBM Hackapalooza – Bluehack Hackathon 2017
  - 1st. Place – 12th. Creativity and Innovation Contest at the University of Guanajuato 2017
  - 1st. Place – Centro Fox National Hackathon 2017
  - 1st. Place – 6th. Creativity and Innovation Contest, DCEA-UG 2016
  - Silver Award – SynBio Giant Jamboree – iGEM  2016
  - 1st. Place – 4th. Creativity and Innovation Contest, DCNE-UG 2016
  - 1st. Place – Fintech – HackBajío Hackathon 2016
